CREATE TABLE `color_themes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`primaryColor` varchar(7) NOT NULL DEFAULT '#003366',
	`secondaryColor` varchar(7) NOT NULL DEFAULT '#D4AF37',
	`accentColor` varchar(7) NOT NULL DEFAULT '#0066CC',
	`textColor` varchar(7) NOT NULL DEFAULT '#333333',
	`textLightColor` varchar(7) NOT NULL DEFAULT '#666666',
	`backgroundColor` varchar(7) NOT NULL DEFAULT '#FFFFFF',
	`surfaceColor` varchar(7) NOT NULL DEFAULT '#F5F5F5',
	`searchBgColor` varchar(7) NOT NULL DEFAULT '#003366',
	`searchTextColor` varchar(7) NOT NULL DEFAULT '#FFFFFF',
	`searchBorderColor` varchar(7) NOT NULL DEFAULT '#D4AF37',
	`isActive` boolean NOT NULL DEFAULT false,
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `color_themes_id` PRIMARY KEY(`id`)
);
